# Some inputs are incompatible. Splitting module run into groups for integration tests
# to make sure it runs without errors.
module_order:
  - bclconvert:
      name: 'bclconvert (28 cycles)'
      info: 'bclconvert (28 cycles)'
      path_filters:
          - '*/3.9.3/*'
  - bclconvert:
      name: 'bclconvert (151 cycle)'
      info: 'bclconvert (151 cycle)'
      path_filters_exclude:
          - '*/3.9.3/*'
  - preseq:
      name: 'Preseq (bases)'
      info: 'Preseq from base count inputs'
      path_filters:
          - '*gc_extrap/preseq_sample_9.txt'
  - preseq:
      name: 'Preseq (reads)'
      info: 'Preseq from read count inputs'
      path_filters_exclude:
          - '*gc_extrap/preseq_sample_9.txt'
